import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Product from './models/Product.js';
import connectDB from './config/db.js';

dotenv.config();

connectDB();

const products = [
    {
        id: 1,
        name: 'Cyberpunk Hoodie',
        category: 'Hoodies',
        gender: 'Men',
        price: 2499,
        originalPrice: 3499,
        image: 'https://images.unsplash.com/photo-1578681994506-b8f463449011?q=80&w=1000&auto=format&fit=crop',
        images: [
            'https://images.unsplash.com/photo-1578681994506-b8f463449011?q=80&w=1000&auto=format&fit=crop',
            'https://images.unsplash.com/photo-1556821840-3a63f95609a7?q=80&w=1000&auto=format&fit=crop'
        ],
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        colors: ['Black', 'Neon Cyan', 'Purple'],
        description: 'Premium cyberpunk-inspired hoodie with neon accents. Made from high-quality cotton blend for maximum comfort.',
        isNewArrival: true,
        rating: 4.5,
        reviews: 24,
        stock: 15
    },
    {
        id: 2,
        name: 'Tech Noir Hoodie',
        category: 'Hoodies',
        gender: 'Men',
        price: 2299,
        originalPrice: 2999,
        image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?q=80&w=1000&auto=format&fit=crop',
        images: ['https://images.unsplash.com/photo-1556821840-3a63f95609a7?q=80&w=1000&auto=format&fit=crop'],
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['Black', 'Gray'],
        description: 'Minimalist tech-inspired hoodie with subtle geometric patterns.',
        isNewArrival: false,
        rating: 4.3,
        reviews: 18,
        stock: 20
    },
    {
        id: 3,
        name: 'Holographic Tee',
        category: 'T-Shirts',
        gender: 'Men',
        price: 899,
        originalPrice: 1299,
        image: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?q=80&w=1000&auto=format&fit=crop',
        images: ['https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?q=80&w=1000&auto=format&fit=crop'],
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        colors: ['White', 'Black', 'Cyan'],
        description: 'Futuristic t-shirt with holographic print. Breathable fabric perfect for Indian summers.',
        isNewArrival: true,
        rating: 4.7,
        reviews: 42,
        stock: 30
    },
    {
        id: 4,
        name: 'Neon Grid Tee',
        category: 'T-Shirts',
        gender: 'Men',
        price: 799,
        originalPrice: 999,
        image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?q=80&w=1000&auto=format&fit=crop',
        images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?q=80&w=1000&auto=format&fit=crop'],
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['Black', 'Navy'],
        description: 'Geometric grid pattern with neon highlights. Premium cotton fabric.',
        isNewArrival: false,
        rating: 4.4,
        reviews: 31,
        stock: 25
    },
    {
        id: 5,
        name: 'Neon Cargo Pants',
        category: 'Pants',
        gender: 'Men',
        price: 1899,
        originalPrice: 2499,
        image: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?q=80&w=1000&auto=format&fit=crop',
        images: ['https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?q=80&w=1000&auto=format&fit=crop'],
        sizes: ['28', '30', '32', '34', '36'],
        colors: ['Black', 'Olive', 'Gray'],
        description: 'Tactical cargo pants with multiple pockets. Durable and stylish.',
        isNewArrival: false,
        rating: 4.6,
        reviews: 28,
        stock: 18
    },
    {
        id: 6,
        name: 'Tech Joggers',
        category: 'Pants',
        gender: 'Men',
        price: 1699,
        originalPrice: 2199,
        image: 'https://images.unsplash.com/photo-1555689502-c4b22d76c56f?q=80&w=1000&auto=format&fit=crop',
        images: ['https://images.unsplash.com/photo-1555689502-c4b22d76c56f?q=80&w=1000&auto=format&fit=crop'],
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['Black', 'Charcoal'],
        description: 'Comfortable tech joggers with zippered pockets. Perfect for casual wear.',
        isNewArrival: true,
        rating: 4.5,
        reviews: 35,
        stock: 22
    },
    {
        id: 7,
        name: 'Techwear Vest',
        category: 'Accessories',
        gender: 'Unisex',
        price: 3499,
        originalPrice: 4499,
        image: 'https://images.unsplash.com/photo-1559563458-527698bf5295?q=80&w=1000&auto=format&fit=crop',
        images: ['https://images.unsplash.com/photo-1559563458-527698bf5295?q=80&w=1000&auto=format&fit=crop'],
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['Black'],
        description: 'Multi-pocket techwear vest. Water-resistant material with adjustable straps.',
        isNewArrival: false,
        rating: 4.8,
        reviews: 16,
        stock: 10
    },
    {
        id: 8,
        name: 'Cyber Backpack',
        category: 'Accessories',
        gender: 'Unisex',
        price: 2999,
        originalPrice: 3999,
        image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=1000&auto=format&fit=crop',
        images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=1000&auto=format&fit=crop'],
        sizes: ['One Size'],
        colors: ['Black', 'Gray'],
        description: 'Futuristic backpack with LED strips. USB charging port included.',
        isNewArrival: true,
        rating: 4.9,
        reviews: 52,
        stock: 12
    },
    {
        id: 9,
        name: 'Matrix Oversized Tee',
        category: 'T-Shirts',
        gender: 'Women',
        price: 999,
        originalPrice: 1499,
        image: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?q=80&w=1000&auto=format&fit=crop',
        images: ['https://images.unsplash.com/photo-1618354691373-d851c5c3a990?q=80&w=1000&auto=format&fit=crop'],
        sizes: ['XS', 'S', 'M', 'L', 'XL'],
        colors: ['Black', 'White'],
        description: 'Oversized fit with matrix-inspired graphics. 100% cotton.',
        isNewArrival: true,
        rating: 4.6,
        reviews: 38,
        stock: 28
    },
    {
        id: 10,
        name: 'Urban Utility Jacket',
        category: 'Hoodies',
        gender: 'Women',
        price: 3299,
        originalPrice: 4299,
        image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?q=80&w=1000&auto=format&fit=crop',
        images: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?q=80&w=1000&auto=format&fit=crop'],
        sizes: ['XS', 'S', 'M', 'L'],
        colors: ['Black', 'Olive', 'Navy'],
        description: 'Multi-functional utility jacket with removable hood. Weather-resistant.',
        isNewArrival: false,
        rating: 4.7,
        reviews: 21,
        stock: 14
    },
    // Sarees
    {
        id: 11,
        name: 'Banarasi Silk Saree',
        category: 'Sarees',
        gender: 'Women',
        price: 4999,
        originalPrice: 7999,
        image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=1000&auto=format&fit=crop',
        images: ['https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=1000&auto=format&fit=crop'],
        sizes: ['Free Size'],
        colors: ['Red', 'Maroon', 'Gold'],
        description: 'Traditional Banarasi silk saree with intricate zari work. Perfect for weddings and festive occasions.',
        isNewArrival: true,
        rating: 4.8,
        reviews: 45,
        stock: 20
    },
    {
        id: 12,
        name: 'Kanjivaram Silk Saree',
        category: 'Sarees',
        gender: 'Women',
        price: 5999,
        originalPrice: 8999,
        image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?q=80&w=1000&auto=format&fit=crop',
        images: ['https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?q=80&w=1000&auto=format&fit=crop'],
        sizes: ['Free Size'],
        colors: ['Green', 'Purple', 'Blue'],
        description: 'Authentic Kanjivaram silk saree with traditional temple border. Handwoven with pure silk.',
        isNewArrival: true,
        rating: 4.9,
        reviews: 62,
        stock: 15
    },
    {
        id: 13,
        name: 'Designer Georgette Saree',
        category: 'Sarees',
        gender: 'Women',
        price: 2499,
        originalPrice: 3999,
        image: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?q=80&w=1000&auto=format&fit=crop',
        images: ['https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?q=80&w=1000&auto=format&fit=crop'],
        sizes: ['Free Size'],
        colors: ['Pink', 'Peach', 'Mint Green'],
        description: 'Lightweight georgette saree with modern prints. Perfect for parties and casual events.',
        isNewArrival: false,
        rating: 4.5,
        reviews: 38,
        stock: 30
    },
    // Kurtas
    {
        id: 14,
        name: 'Anarkali Kurta Set',
        category: 'Kurta',
        gender: 'Women',
        price: 1999,
        originalPrice: 2999,
        image: 'https://images.unsplash.com/photo-1583391733981-e8c9e00e44c7?q=80&w=1000&auto=format&fit=crop',
        images: ['https://images.unsplash.com/photo-1583391733981-e8c9e00e44c7?q=80&w=1000&auto=format&fit=crop'],
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        colors: ['Navy Blue', 'Maroon', 'Emerald Green'],
        description: 'Elegant Anarkali kurta with dupatta. Comfortable cotton fabric with beautiful embroidery.',
        isNewArrival: true,
        rating: 4.6,
        reviews: 52,
        stock: 25
    },
    {
        id: 15,
        name: 'Straight Cut Kurta',
        category: 'Kurta',
        gender: 'Women',
        price: 1299,
        originalPrice: 1999,
        image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=1000&auto=format&fit=crop',
        images: ['https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=1000&auto=format&fit=crop'],
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        colors: ['White', 'Black', 'Mustard'],
        description: 'Simple straight cut kurta perfect for daily wear. Breathable cotton blend fabric.',
        isNewArrival: false,
        rating: 4.4,
        reviews: 67,
        stock: 40
    },
    {
        id: 16,
        name: 'Printed A-Line Kurta',
        category: 'Kurta',
        gender: 'Women',
        price: 1599,
        originalPrice: 2499,
        image: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?q=80&w=1000&auto=format&fit=crop',
        images: ['https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?q=80&w=1000&auto=format&fit=crop'],
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['Floral Print', 'Abstract Print', 'Geometric Print'],
        description: 'Trendy A-line kurta with contemporary prints. Perfect for casual outings.',
        isNewArrival: true,
        rating: 4.5,
        reviews: 41,
        stock: 35
    },
    // Half Sarees
    {
        id: 17,
        name: 'Traditional Half Saree',
        category: 'Half Saree',
        gender: 'Women',
        price: 3499,
        originalPrice: 5499,
        image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?q=80&w=1000&auto=format&fit=crop',
        images: ['https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?q=80&w=1000&auto=format&fit=crop'],
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['Red & Gold', 'Green & Gold', 'Pink & Silver'],
        description: 'Beautiful traditional half saree (Langa Voni) with embroidered blouse and dupatta. Perfect for festivals.',
        isNewArrival: true,
        rating: 4.7,
        reviews: 28,
        stock: 18
    },
    {
        id: 18,
        name: 'Designer Lehenga Half Saree',
        category: 'Half Saree',
        gender: 'Women',
        price: 4999,
        originalPrice: 7999,
        image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=1000&auto=format&fit=crop',
        images: ['https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=1000&auto=format&fit=crop'],
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['Royal Blue', 'Magenta', 'Turquoise'],
        description: 'Stunning designer half saree with heavy work. Ideal for weddings and special occasions.',
        isNewArrival: true,
        rating: 4.8,
        reviews: 35,
        stock: 12
    },
    {
        id: 19,
        name: 'Silk Half Saree Set',
        category: 'Half Saree',
        gender: 'Women',
        price: 3999,
        originalPrice: 5999,
        image: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?q=80&w=1000&auto=format&fit=crop',
        images: ['https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?q=80&w=1000&auto=format&fit=crop'],
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['Peach', 'Lavender', 'Mint'],
        description: 'Elegant silk half saree with delicate embroidery. Comes with matching blouse and dupatta.',
        isNewArrival: false,
        rating: 4.6,
        reviews: 22,
        stock: 16
    },
    // Western Wear
    {
        id: 20,
        name: 'Denim Jacket',
        category: 'Western',
        gender: 'Women',
        price: 1899,
        originalPrice: 2999,
        image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?q=80&w=1000&auto=format&fit=crop',
        images: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?q=80&w=1000&auto=format&fit=crop'],
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['Light Blue', 'Dark Blue', 'Black'],
        description: 'Classic denim jacket with modern fit. Perfect for layering and casual outings.',
        isNewArrival: true,
        rating: 4.5,
        reviews: 48,
        stock: 32
    },
    {
        id: 21,
        name: 'Floral Maxi Dress',
        category: 'Western',
        gender: 'Women',
        price: 2299,
        originalPrice: 3499,
        image: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?q=80&w=1000&auto=format&fit=crop',
        images: ['https://images.unsplash.com/photo-1618354691373-d851c5c3a990?q=80&w=1000&auto=format&fit=crop'],
        sizes: ['XS', 'S', 'M', 'L', 'XL'],
        colors: ['Floral Red', 'Floral Blue', 'Floral Yellow'],
        description: 'Breezy floral maxi dress perfect for summer. Lightweight and comfortable fabric.',
        isNewArrival: true,
        rating: 4.7,
        reviews: 56,
        stock: 28
    },
    {
        id: 22,
        name: 'High-Waist Jeans',
        category: 'Western',
        gender: 'Women',
        price: 1799,
        originalPrice: 2499,
        image: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?q=80&w=1000&auto=format&fit=crop',
        images: ['https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?q=80&w=1000&auto=format&fit=crop'],
        sizes: ['26', '28', '30', '32', '34'],
        colors: ['Blue', 'Black', 'Grey'],
        description: 'Trendy high-waist jeans with perfect fit. Stretchable denim for all-day comfort.',
        isNewArrival: false,
        rating: 4.6,
        reviews: 73,
        stock: 45
    }
];

const importData = async () => {
    try {
        await Product.deleteMany();

        await Product.insertMany(products);

        console.log('Data Imported!');
        process.exit();
    } catch (error) {
        console.error(`${error}`);
        process.exit(1);
    }
};

importData();
